complexity:
  LongMethod:
    allowedLines: 80
  LongParameterList:
    allowedFunctionParameters: 8
    allowedConstructorParameters: 8
  CyclomaticComplexMethod:
    allowedComplexity: 20
  TooManyFunctions:
    active: false
  NestedBlockDepth:
    allowedDepth: 6

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
  ForbiddenComment:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
