complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
  CyclomaticComplexMethod:
    threshold: 20
  TooManyFunctions:
    active: false
  NestedBlockDepth:
    threshold: 6

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
  ForbiddenComment:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false
